name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pack
        shell: pwsh
        run: ./pack.ps1 -Version "${{ github.ref_name }}"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "OreUI Theme MC1.12.2 ${{ github.ref_name }}"
          files: "*.zip"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
